// Generated by CoffeeScript 1.6.3
Meteor.startup(function() {
  bootbox.animate(false);
  Toast.defaults.width = '400px';
  return Toast.defaults.displayDuration = 1000;
});

Meteor.subscribe('players');

Template.navbar.events({
  'click .sort_by_name': function() {
    return Session.set('sort_by_name', true);
  },
  'click .sort_by_score': function() {
    return Session.set('sort_by_name', false);
  },
  'click .reset_data': function() {
    return bootbox.confirm('Are you sure you want to reset the data?', 'No', 'Yes', function(confirmed) {
      if (confirmed) {
        return Meteor.call('reset_data', function(error) {
          return Toast.error(error.reason);
        });
      }
    });
  }
});

Template.leaderboard.players = function() {
  var sort;
  sort = Session.get('sort_by_name') ? {
    name: 1
  } : {
    score: -1
  };
  return Players.find({}, {
    sort: sort
  });
};

Template.leaderboard.events({
  'click #add_button, keyup #player_name': function(evt) {
    var input;
    if (evt.type === 'keyup' && evt.which !== 13) {
      return;
    }
    input = $('#player_name');
    if (input.val()) {
      Players.insert({
        name: input.val(),
        score: Math.floor(Math.random() * 10) * 5
      }, function(err) {
        if (err) {
          return Toast.error(err.reason);
        }
      });
      return input.val('');
    } else {
      return Toast.warning('Enter New Player');
    }
  }
});

Template.player.events({
  'click .increment': function() {
    return Players.update(this._id, {
      $inc: {
        score: 5
      }
    }, function(err) {
      if (err) {
        return Toast.error(err.reason);
      }
    });
  },
  'click .remove': function() {
    return Players.remove(this._id, function(err) {
      if (err) {
        return Toast.error(err.reason);
      }
    });
  },
  'click': function() {
    return $('.tooltip').remove();
  }
});

Template.player.rendered = function() {
  return $('[rel=tooltip]').tooltip();
};
