// Generated by CoffeeScript 1.6.3
Meteor.publish('players', function() {
  return Players.find();
});

Meteor.startup(function() {
  if (Players.find().count() === 0) {
    return Players.reset_data();
  }
});

Meteor.methods({
  reset_data: function() {
    if (this.userId) {
      return Players.reset_data();
    } else {
      throw new Meteor.Error(401, 'Access denied');
    }
  }
});

Players.allow({
  insert: function(userId) {
    return userId;
  },
  update: function(userId) {
    return userId;
  },
  remove: function(userId) {
    return userId;
  }
});

Players.reset_data = function() {
  var name, names, _i, _len, _results;
  names = ['Ada Lovelace', 'Grace Hopper', 'Marie Curie', 'Carl Friedrich Gauss', 'Nikola Tesla', 'Claude Shannon', 'Issac Newton'];
  console.log('Resetting data.');
  Players.remove({});
  _results = [];
  for (_i = 0, _len = names.length; _i < _len; _i++) {
    name = names[_i];
    _results.push(Players.insert({
      name: name,
      score: Math.floor(Math.random() * 10) * 5
    }));
  }
  return _results;
};
